version: '3.7'

services:

  psqldb:
    ports:
      - 5432:5432

  app:
    command: flask run --host=0.0.0.0
    volumes:
      - ./:/app
    environment:
      FLASK_DEBUG: 1

# volumes:
  # fyp_psql_data: