version: '3.7'

services:

  psqldb:
    image: postgres:13
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_PASSWORD=letmein_justkidding
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: fyp_app_ubuntu
    # build: .
    # command: gunicorn -b :5000 --access-logfile - --error-logfile - chatbot:app
    volumes:
      - /var/log/gunicorn:/var/log/gunicorn
    command: gunicorn -b :5000 --log-config log.conf chatbot:app
    ports:
      - "5001:5000"
    depends_on:
      psqldb:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1

# volumes:
  # fyp_psql_data:
